import Follow from "./components/Follow";
import Footer from "./components/Footer";
import Navegation from "./components/Navegation";
import Subnavegation from "./components/Subnavegation";
import "./globals.css";
import { Playfair_Display } from "next/font/google";

const playfair = Playfair_Display({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={playfair.className}>
        <header>
          <Navegation />
        </header>
        <main className="w-full relative font-semibold">
          <img
            src="/images/background.jpg"
            alt="background"
            className="object-cover w-full absolute -z-10"
          />
          <Follow />
          <Subnavegation />
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
